### ISSUE TITLE
PKLot database structure

### ISSUE THREAD

**Issue by tcinbis** [dalmia/WannaPark#1]
Hey, first of all great project! I tried to recreate your parking_lot_detection python scripts, but got some problems in `train_detection`.
I downloaded the following database here [PKLot.tar.gz](http://www.inf.ufpr.br/lesoliveira/download/) but it seems to have a different structure compared to your database.

Could you give me an example,  what your directory looked like or maybe even upload it somewhere to share it? I could offer you some temporary cloud storage.

Thanks in advance!

**Comment by dalmia** [comment]
Thanks for the comment @tcinbis. Please share the traceback (a.k.a. the error that you are getting) so that I can understand what's going wrong. 
Also, I downloaded the dataset from: https://web.inf.ufpr.br/vri/databases/parking-lot-database/

Let me know if there's any problem!

**Comment by tcinbis** [comment]
Hey there, sorry for the late answer. We got the wrong database from your ftp server. Now it works perfectly fine. Thanks!

**Comment by rashmisgh** [comment]
hey i also tried to run train_detection.py i am facing this error while train the PKLot dataset.
here is the error:- 
Traceback (most recent call last):
  File "train_detection.py", line 95, in <module>
    validX[counter_test] = img
IndexError: index 216649 is out of bounds for axis 0 with size 216649

**Comment by vishalmishra14** [comment]
hey i also tried to run train_detection.py i am facing this error while train the PKLot dataset.
here is the error:-
Traceback (most recent call last):
File "train_detection.py", line 95, in 
validX[counter_test] = img
IndexError: index 216649 is out of bounds for axis 0 with size 216649
